version: '3'
vars:
  basedir: '{{ .TASKFILE_DIR | relPath .npm_config_local_prefix }}'
tasks:
  act:
    internal: true
    requires:
      vars: [workflows]
    <<: &act
      desc: 'Run: {{ .workflows }}'
      dir: '{{ .npm_config_local_prefix }}'
      cmd: >-
        act-js
        --container-architecture linux/{{ default ARCH .architecture }}
        --workflows {{ .workflows }}
        {{ .CLI_ARGS }}
  clear-cache:
    cmd: rm -rf "${npm_config_local_prefix}/node_modules/.act"
  default:
    desc: Just checks if the action works with default settings.
    cmd:
      task: act
      vars:
        CLI_ARGS: >-
          --job save-cache
          --no-cache-server
        workflows: .github/workflows/e2e.yml
  historic: &run-global-workflow
    <<: *act
    vars:
      architecture: amd64
      workflows: .github/workflows/e2e-{{ .TASK }}.yml
  proxy: *run-global-workflow
  test:
    <<: *act
    deps: [clear-cache]
    vars:
      workflows: .github/workflows/e2e.yml
  fallback-to-historic-master: &run-local-workflow
    <<: *act
    deps: [clear-cache]
    vars:
      workflows: '{{ .basedir }}/workflows/{{ .TASK }}.yml'
  move-to-historic: *run-local-workflow
  tlpretest: *run-local-workflow

  cache-on-failure:
    <<: &cache-on-failure
      vars:
        workflow: '{{ .TASK | splitList ":" | first }}'
        case: '{{ .TASK | trimPrefix .workflow | trimPrefix ":" }}'
      desc: >-
        Run: {{ .basedir }}/workflows/{{ .workflow }}.yml
        {{ if .case }}({{ .case }}){{ end }}
      cmd: >-
        vitest {{- if .case }} --testNamePattern '^{{ .case }}$'{{ end }}
  cache-on-failure:default: *cache-on-failure
  cache-on-failure:with-0: *cache-on-failure
  cache-on-failure:with-1: *cache-on-failure
  cache-on-failure:with-true: *cache-on-failure
  cache-on-failure:with-: *cache-on-failure
