name: Setup TeXLive Action
description: A GitHub Action to set up TeX Live.
author: '@teatimeguest'

inputs:
  cache:
    description: >-
      Enable caching for `TEXDIR`.
    default: true
    required: false
  package-file:
    description: >-
      File containing TeX package names to be installed.
      The file format is whitespace-delimited, and
      everything after a `#` is treated as a comment.
      `DEPENDS.txt` format is also acceptable.
    default: ''
    required: false
  packages:
    description: >-
      Whitespace-separated TeX package names to be installed.
      Schemes and collections can also be specified.
    default: ''
    required: false
  prefix:
    description: >-
      TeX Live installation prefix.
      This has the same effect as `TEXLIVE_INSTALL_PREFIX`.
      The default is `$RUNNER_TEMP/setup-texlive`.
    required: false
  tlcontrib:
    description: >-
      Set up TLContrib as an additional TeX package repository.
      This input will be ignored if an older version is specified for `version`.
    default: false
    required: false
  update-all-packages:
    description: >-
      Update all TeX packages when restoring cache.
      The default is `false` and the action updates only `tlmgr`.
    default: false
    required: false
  version:
    description: >-
      TeX Live version to install.
      Supported versions are `2008` to `2022` for Linux and Windows,
      `2013` to `2022` for macOS.
      If set to `latest`, the latest version will be installed.
    default: latest
    required: false

outputs:
  cache-hit:
    description: >-
      A boolean value to indicate if a cache was hit.

runs:
  using: node16
  main: dist/index.js
  post: dist/index.js
  post-if: success()

branding:
  color: green
  icon: type
