name: Setup TeXLive Action
description: A GitHub Action to set up TeX Live.
author: '@teatimeguest'
inputs:
  cache:
    description: >-
      Enable caching for `TEXDIR`.
    default: true
    required: false
  package-file:
    description: >-
      File containing the names of TeX packages to be installed,
      delimited by whitespaces.
      Everything after a `#` is treated as a comment.
      The `DEPENDS.txt` format is also supported.
    default: ''
    required: false
  packages:
    description: >-
      Whitespace-separated TeX package names to be installed.
      Schemes and collections are also acceptable.
    default: ''
    required: false
  prefix:
    description: >-
      TeX Live installation prefix.
      This has the same effect as `TEXLIVE_INSTALL_PREFIX`.
      Defaults to `$RUNNER_TEMP/setup-texlive`.
    required: false
  tlcontrib:
    description: >-
      Set up TLContrib as an additional TeX package repository.
      This input will be ignored for older versions.
    default: false
    required: false
  update-all-packages:
    description: >-
      Update all TeX packages when cache restored.
      The default is `false` and the action will update only `tlmgr`.
    default: false
    required: false
  version:
    description: >-
      TeX Live version to install.
      Supported values are `2008` to `2022`, and `latest`.
    default: latest
    required: false
outputs:
  cache-hit:
    description: A boolean value to indicate if a cache was hit.
  version:
    description: The installed TeX Live version.
runs:
  using: node16
  main: dist/index.js
  post: dist/index.js
  post-if: success()
branding:
  color: green
  icon: type
