on: workflow_dispatch
jobs:
  save-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup TeX Live
        id: setup
        uses: ./
        with:
          version: 2023
      - if: fromJSON(steps.setup.outputs.cache-restored)
        run: exit 1
      - run: >-
          tlmgr option repository ctan
  restore-cache:
    needs: save-cache
    runs-on: ubuntu-latest
    container:
      image: node:20.0
      options: --add-host=ftp.math.utah.edu:127.0.0.1
    steps:
      - uses: actions/checkout@v4
      - name: Setup TeX Live
        id: setup
        uses: ./
        with:
          version: 2023
      - if: ${{ !fromJSON(steps.setup.outputs.cache-hit) }}
        run: exit 1
      - run: >-
          tlmgr option repository | grep -F tug.org
