name: Dependabot
on:
  workflow_run:
    workflows: ['Pull request']
    types: [completed]
permissions:
  contents: write
  pull-requests: write
jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.event.sender.login == 'dependabot[bot]'
    steps:
      - name: Try to merge
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PR: ${{ github.event.workflow_run.pull_requests[0].number }}
        run: >-
          gh pr merge -sd "${PR}"
